source 'https://rubygems.org'

gem 'rails', '3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'nokogiri'

gem 'omniauth-shibboleth', :git => "git://github.com/beffa/omniauth-shibboleth.git"
